### ISSUE TITLE
 /usr/share/yunohost/hooks/post_user_create/50-wallabag  remaining after uninstall

### ISSUE THREAD

**Issue by JocelynDelalande** [abeudin/wallabag_ynh#23]
I installed and then removed wallabag app. So current state is that wallabag_ynh is uninstalled.

After that, at ynh user creation, I get this message, and it makes user creation fail :

```
Échec de l’exécution du script : /usr/share/yunohost/hooks/post_user_create/50-wallabag
rm: impossible de supprimer '/tmp/useridwallabag': Aucun fichier ou dossier de ce type
ERROR 1049 (42000): Unknown database 'wallabag'
ERROR 1049 (42000): Unknown database 'wallabag'
ERROR 1049 (42000): Unknown database 'wallabag'
```

I get rid of this error by simply removing the */usr/share/yunohost/hooks/post_user_create/50-wallabag* file. But i think it has been let around by wallabag uninstall script, which looks like a bug.

**Comment by lapineige** [comment]
Just to be sure: your issue concerns wallabag v1 and not wallabag v2 (https://github.com/YunoHost-Apps/wallabag2_ynh), right ?

**Comment by JocelynDelalande** [comment]
I have no idea to be honest (now the app is uninstalled). What I can see from the logs is that the app i installed had created a /home/wallabag2 folder.

**Comment by lapineige** [comment]
When you used the app, did it look like Wallabag2 (https://github.com/YunoHost-Apps/wallabag2_ynh/#screenshots) ?

If it's a wallabag2 folder, it's probably Wallabag2 app, so please open an issue here https://github.com/YunoHost-Apps/wallabag2_ynh 🙂

**Comment by JocelynDelalande** [comment]
Yes you are probably right, wallabag 2 but now all that is a bit far in my memory & my logs, so, I'll just close this one for now.
