### ISSUE TITLE
[SECURITY] Wallabag database password readable by all users

### ISSUE THREAD

**Issue by Jules-Bertholet** [abeudin/wallabag_ynh#25]
This password can be stored in `$final_path/var/cache/prod/appProdProjectContainer.php`, which all users can read.

**Comment by lapineige** [comment]
I suppose we should change the access rights for this file ?

**Comment by Jules-Bertholet** [comment]
Ideally the access rights for the whole folder should be restricted only to users that need the access.

**Comment by lapineige** [comment]
I wonder which users should have access…

**Comment by Jules-Bertholet** [comment]
Wait, I realized this issue is in the wrong repo, I meant it for `wallabag2`, I will close this and recreate it there
