### ISSUE TITLE
Cannot access with external application 

### ISSUE THREAD

**Issue by yusf** [abeudin/wallabag_ynh#6]
Using the iOS app (assuming the same goes for the other apps) I cannot access my Wallabag content. This is because all apps resides behind YunoHost's SSO system. Exceptions for specific file paths in order to expose those ones to the world can be put in **/etc/ssowat/conf.json** like so
>"skipped_urls": [
>   "/yunohost/api"
>],

The problem is, I think, that the Wallabag API is reached on the root path ( /wallabag ), making it impossible to separate API calls from web access.

How to solve this issue?

Adding 
>"/wallabag",

to the skipped_urls list exposes the whole application and also breaks it away from the SSO system…

**Comment by ckiw** [comment]
I get the problem too, the client (app) get redirected toward ssowat even if it's a route not protected in wallabag by credentials but with token, so the client get an error.

**Comment by stevenroose** [comment]
This should probably be solved by excluding the api endpoint from the ssowat config. I'm no nginx expert, but I think it can't be that hard if you have some experience with nginx...

**Comment by abeudin** [comment]
i fix the problem with the last version you can try it 
yunohost app upgrade wallabag -u https://github.com/abeudin/wallabag_ynh.git
